export {
  validateEventConfig,
  validateTheme,
  validateBadgesConfig,
  validateFeatures,
  KNOWN_FEATURE_KEYS,
  TRACK_LETTER_RE,
  LEGAL_KEYS,
  SOCIAL_KEYS,
  SOCIAL_HANDLE_KEYS,
  MAX_SOCIAL_LABEL_LENGTH,
  MILESTONE_KEYS,
  MAX_MILESTONES,
  MAX_MILESTONE_LABEL_LENGTH,
  MAX_REGISTRATION_GOAL,
  isHttpsUrl,
  httpsUrlHref,
} from './schema.cjs';
